services:
  db:
    image: postgres:16-alpine
    container_name: feedback_app_db_dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: feedback_app_redis_dev
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

volumes:
  pg_data_dev:
  redis_data_dev:
