services:
  db:
    image: postgres:16-alpine
    container_name: feedback_app_db_dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data_dev: 