services:
  db:
    image: postgres:16-alpine
    container_name: feedback_app_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: feedback_app_redis
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    image: feedback_app:latest
    container_name: feedback_app_worker
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    command: bundle exec sidekiq -q default -q maintenance

  web:
    build: .
    image: feedback_app:latest
    container_name: feedback_app_web
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: "1"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:80"

volumes:
  pg_data:
  redis_data:
