version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: feedback_app_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    image: feedback_app:latest
    container_name: feedback_app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      RAILS_LOG_TO_STDOUT: "1"
    ports:
      - "80:80"

volumes:
  pg_data: 